-- ─── Coach tables ─────────────────────────────────────────────────────────────

-- Invite codes generated by athletes, accepted by coaches
create table if not exists coach_invites (
  id          uuid primary key default gen_random_uuid(),
  athlete_id  uuid references users(id) on delete cascade not null,
  code        text not null unique,
  status      text not null default 'pending', -- pending | accepted | revoked
  expires_at  timestamptz not null default now() + interval '48 hours',
  coach_id    uuid references users(id) on delete set null,
  created_at  timestamptz default now() not null
);

-- Active coach–athlete relationships
create table if not exists coach_athletes (
  id          uuid primary key default gen_random_uuid(),
  coach_id    uuid references users(id) on delete cascade not null,
  athlete_id  uuid references users(id) on delete cascade not null,
  active      boolean not null default true,
  created_at  timestamptz default now() not null,
  unique (coach_id, athlete_id)
);

-- Per-relationship privacy controls (athlete decides what coach can see)
create table if not exists coach_privacy_settings (
  id               uuid primary key default gen_random_uuid(),
  athlete_id       uuid references users(id) on delete cascade not null,
  coach_id         uuid references users(id) on delete cascade not null,
  see_activities   boolean not null default true,
  see_nutrition    boolean not null default false,
  see_meals        boolean not null default false,
  see_weight       boolean not null default false,
  unique (athlete_id, coach_id)
);

-- Notes and workout assignments from coach to athlete
create table if not exists coach_notes (
  id                  uuid primary key default gen_random_uuid(),
  coach_id            uuid references users(id) on delete cascade not null,
  athlete_id          uuid references users(id) on delete cascade not null,
  content             text not null,
  note_type           text not null default 'note', -- note | workout | nutrition
  planned_workout_id  uuid references planned_workouts(id) on delete set null,
  created_at          timestamptz default now() not null
);

-- ─── RLS ──────────────────────────────────────────────────────────────────────

alter table coach_invites         enable row level security;
alter table coach_athletes        enable row level security;
alter table coach_privacy_settings enable row level security;
alter table coach_notes           enable row level security;

-- coach_invites: athlete manages their own; coach reads the row they accepted
create policy "athlete_own_invites" on coach_invites
  for all using (athlete_id = auth.uid());

create policy "coach_read_accepted_invite" on coach_invites
  for select using (coach_id = auth.uid());

-- coach_athletes: both parties can read; athlete can delete (to revoke access)
create policy "coach_or_athlete_read_relationship" on coach_athletes
  for select using (coach_id = auth.uid() or athlete_id = auth.uid());

create policy "athlete_delete_relationship" on coach_athletes
  for delete using (athlete_id = auth.uid());

-- coach_privacy_settings: athlete full control; coach can read their own row
create policy "athlete_own_privacy" on coach_privacy_settings
  for all using (athlete_id = auth.uid());

create policy "coach_read_privacy" on coach_privacy_settings
  for select using (coach_id = auth.uid());

-- coach_notes: coach writes; both can read
create policy "coach_write_notes" on coach_notes
  for insert with check (coach_id = auth.uid());

create policy "coach_read_own_notes" on coach_notes
  for select using (coach_id = auth.uid());

create policy "athlete_read_notes" on coach_notes
  for select using (athlete_id = auth.uid());

create policy "coach_update_own_notes" on coach_notes
  for update using (coach_id = auth.uid());

create policy "coach_delete_own_notes" on coach_notes
  for delete using (coach_id = auth.uid());

-- ─── coach_can_view() ─────────────────────────────────────────────────────────
-- Security-definer function so it can query coach_athletes + coach_privacy_settings
-- without the caller needing direct access to those tables.
-- data_type: 'activities' | 'nutrition' | 'meals' | 'weight' | 'profile'
create or replace function coach_can_view(p_athlete_id uuid, p_data_type text)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1
    from   coach_athletes ca
    join   coach_privacy_settings cps
           on  cps.coach_id   = ca.coach_id
           and cps.athlete_id = ca.athlete_id
    where  ca.coach_id   = auth.uid()
      and  ca.athlete_id = p_athlete_id
      and  ca.active     = true
      and  (
             p_data_type = 'profile'
          or (p_data_type = 'activities' and cps.see_activities)
          or (p_data_type = 'nutrition'  and cps.see_nutrition)
          or (p_data_type = 'meals'      and cps.see_meals)
          or (p_data_type = 'weight'     and cps.see_weight)
      )
  )
$$;

-- ─── Extended RLS on existing tables ──────────────────────────────────────────

-- activities: coach can read if athlete granted access
create policy "coach_view_activities" on activities
  for select using (coach_can_view(user_id, 'activities'));

-- food_logs: coach can read if athlete granted nutrition access
create policy "coach_view_nutrition" on food_logs
  for select using (coach_can_view(user_id, 'nutrition'));

-- meal_templates: coach can read if athlete granted meals access
create policy "coach_view_meal_templates" on meal_templates
  for select using (coach_can_view(user_id, 'meals'));

-- meal_checks: coach can read if athlete granted meals access
create policy "coach_view_meal_checks" on meal_checks
  for select using (coach_can_view(user_id, 'meals'));

-- users: coach can read basic profile of connected athletes
create policy "coach_view_profile" on users
  for select using (coach_can_view(id, 'profile'));
