export interface CommonFood {
  name: string
  kcal: number
  protein_g?: number
  fat_g?: number
  carb_g?: number
}

export const COMMON_FOOD_CATEGORIES: { category: string; items: CommonFood[] }[] = [
  {
    category: 'Fruit',
    items: [
      { name: 'Apple (medium)', kcal: 72, carb_g: 19 },
      { name: 'Banana (medium)', kcal: 89, carb_g: 23, protein_g: 1 },
      { name: 'Orange (medium)', kcal: 62, carb_g: 15 },
      { name: 'Pear (medium)', kcal: 101, carb_g: 27 },
      { name: 'Peach (medium)', kcal: 59, carb_g: 14 },
      { name: 'Kiwi (1 piece)', kcal: 42, carb_g: 10, protein_g: 1 },
      { name: 'Watermelon (200g)', kcal: 60, carb_g: 15 },
      { name: 'Pineapple (100g)', kcal: 50, carb_g: 13 },
      { name: 'Raspberries (100g)', kcal: 52, carb_g: 12, protein_g: 1 },
      { name: 'Blueberries (100g)', kcal: 57, carb_g: 14, protein_g: 1 },
      { name: 'Strawberries (100g)', kcal: 32, carb_g: 8 },
      { name: 'Mango (100g)', kcal: 60, carb_g: 15 },
      { name: 'Grapes (100g)', kcal: 69, carb_g: 18 },
      { name: 'Cherries (100g)', kcal: 63, carb_g: 16 },
      { name: 'Melon / cantaloupe (100g)', kcal: 34, carb_g: 8 },
    ],
  },
  {
    category: 'Vegetables',
    items: [
      { name: 'Broccoli (100g)', kcal: 34, carb_g: 7, protein_g: 3 },
      { name: 'Spinach (100g)', kcal: 23, carb_g: 4, protein_g: 3 },
      { name: 'Kale (100g)', kcal: 49, carb_g: 9, protein_g: 4 },
      { name: 'Carrot (medium)', kcal: 25, carb_g: 6 },
      { name: 'Bell pepper (medium)', kcal: 31, carb_g: 7, protein_g: 1 },
      { name: 'Tomato (medium)', kcal: 22, carb_g: 5 },
      { name: 'Cherry tomatoes (100g)', kcal: 18, carb_g: 4 },
      { name: 'Cucumber (100g)', kcal: 15, carb_g: 4 },
      { name: 'Zucchini (100g)', kcal: 17, carb_g: 3, protein_g: 1 },
      { name: 'Courgette (100g)', kcal: 17, carb_g: 3, protein_g: 1 },
      { name: 'Cauliflower (100g)', kcal: 25, carb_g: 5, protein_g: 2 },
      { name: 'Green beans (100g)', kcal: 31, carb_g: 7, protein_g: 2 },
      { name: 'Peas (100g)', kcal: 81, carb_g: 14, protein_g: 5 },
      { name: 'Corn / sweetcorn (100g)', kcal: 86, carb_g: 19, protein_g: 3 },
      { name: 'Onion (medium)', kcal: 44, carb_g: 10 },
      { name: 'Garlic (1 clove)', kcal: 4, carb_g: 1 },
      { name: 'Mushrooms (100g)', kcal: 22, carb_g: 3, protein_g: 3 },
      { name: 'Asparagus (100g)', kcal: 20, carb_g: 4, protein_g: 2 },
      { name: 'Sweet potato (medium)', kcal: 103, carb_g: 24, protein_g: 2 },
      { name: 'Potato (medium, boiled)', kcal: 140, carb_g: 32, protein_g: 3 },
      { name: 'Edamame (100g)', kcal: 121, carb_g: 10, protein_g: 11, fat_g: 5 },
      { name: 'Beetroot (100g)', kcal: 43, carb_g: 10, protein_g: 2 },
      { name: 'Lettuce / mixed greens (50g)', kcal: 10, carb_g: 2 },
      { name: 'Avocado (half)', kcal: 120, fat_g: 11, carb_g: 6, protein_g: 2 },
      { name: 'Eggplant / aubergine (100g)', kcal: 25, carb_g: 6, protein_g: 1 },
    ],
  },
  {
    category: 'Bread & Grains',
    items: [
      { name: 'Slice of bread (white)', kcal: 79, carb_g: 15, protein_g: 3, fat_g: 1 },
      { name: 'Slice of bread (whole wheat)', kcal: 69, carb_g: 12, protein_g: 4, fat_g: 1 },
      { name: 'Sourdough (slice)', kcal: 90, carb_g: 18, protein_g: 4, fat_g: 1 },
      { name: 'Bagel (plain)', kcal: 270, carb_g: 53, protein_g: 10, fat_g: 2 },
      { name: 'Croissant', kcal: 231, carb_g: 26, protein_g: 5, fat_g: 12 },
      { name: 'Wrap / tortilla (medium)', kcal: 210, carb_g: 36, protein_g: 5, fat_g: 5 },
      { name: 'Pita bread (1 piece)', kcal: 165, carb_g: 33, protein_g: 5, fat_g: 1 },
      { name: 'Oats (50g uncooked)', kcal: 188, protein_g: 6, fat_g: 3, carb_g: 33 },
      { name: 'Muesli (50g)', kcal: 185, protein_g: 5, fat_g: 4, carb_g: 33 },
      { name: 'Granola (50g)', kcal: 225, protein_g: 5, fat_g: 8, carb_g: 33 },
      { name: 'White rice (100g uncooked)', kcal: 365, protein_g: 7, fat_g: 1, carb_g: 79 },
      { name: 'Brown rice (100g uncooked)', kcal: 362, protein_g: 8, fat_g: 3, carb_g: 76 },
      { name: 'Basmati rice (100g uncooked)', kcal: 356, protein_g: 7, fat_g: 1, carb_g: 78 },
      { name: 'Spaghetti (100g uncooked)', kcal: 371, protein_g: 13, fat_g: 2, carb_g: 74 },
      { name: 'Penne (100g uncooked)', kcal: 371, protein_g: 13, fat_g: 2, carb_g: 74 },
      { name: 'Pasta (wholegrain, 100g uncooked)', kcal: 352, protein_g: 13, fat_g: 2, carb_g: 69 },
      { name: 'Egg noodles (100g uncooked)', kcal: 384, protein_g: 12, fat_g: 4, carb_g: 72 },
      { name: 'Couscous (100g uncooked)', kcal: 376, protein_g: 13, fat_g: 1, carb_g: 77 },
      { name: 'Quinoa (100g uncooked)', kcal: 368, protein_g: 14, fat_g: 6, carb_g: 64 },
      { name: 'Bulgur wheat (100g uncooked)', kcal: 342, protein_g: 12, fat_g: 1, carb_g: 76 },
      { name: 'Lentils (100g dry)', kcal: 352, protein_g: 25, fat_g: 1, carb_g: 60 },
      { name: 'Chickpeas (100g dry)', kcal: 364, protein_g: 19, fat_g: 6, carb_g: 61 },
      { name: 'Kidney beans (100g, canned)', kcal: 92, protein_g: 6, fat_g: 1, carb_g: 17 },
    ],
  },
  {
    category: 'Meat & Fish',
    items: [
      { name: 'Chicken breast (100g)', kcal: 165, protein_g: 31, fat_g: 4 },
      { name: 'Chicken thigh (100g)', kcal: 209, protein_g: 26, fat_g: 11 },
      { name: 'Turkey breast (100g)', kcal: 135, protein_g: 30, fat_g: 1 },
      { name: 'Beef mince 5% fat (100g)', kcal: 137, protein_g: 21, fat_g: 5 },
      { name: 'Beef mince 20% fat (100g)', kcal: 254, protein_g: 17, fat_g: 20 },
      { name: 'Beef steak (100g)', kcal: 271, protein_g: 26, fat_g: 18 },
      { name: 'Pork tenderloin (100g)', kcal: 143, protein_g: 26, fat_g: 4 },
      { name: 'Pork chop (100g)', kcal: 231, protein_g: 25, fat_g: 14 },
      { name: 'Bacon (2 rashers)', kcal: 86, protein_g: 6, fat_g: 7 },
      { name: 'Ham / cooked (50g)', kcal: 65, protein_g: 9, fat_g: 2, carb_g: 2 },
      { name: 'Salmon (100g)', kcal: 208, protein_g: 20, fat_g: 13 },
      { name: 'Cod (100g)', kcal: 82, protein_g: 18, fat_g: 1 },
      { name: 'Tuna in water (100g)', kcal: 116, protein_g: 26, fat_g: 1 },
      { name: 'Tuna in oil (100g)', kcal: 198, protein_g: 25, fat_g: 11 },
      { name: 'Mackerel (100g)', kcal: 205, protein_g: 19, fat_g: 14 },
      { name: 'Tilapia (100g)', kcal: 96, protein_g: 20, fat_g: 2 },
      { name: 'Shrimp / prawns (100g)', kcal: 85, protein_g: 18, fat_g: 1 },
      { name: 'Lamb mince (100g)', kcal: 282, protein_g: 18, fat_g: 23 },
      { name: 'Tofu (100g)', kcal: 76, protein_g: 8, fat_g: 5, carb_g: 2 },
      { name: 'Tempeh (100g)', kcal: 195, protein_g: 19, fat_g: 11, carb_g: 9 },
    ],
  },
  {
    category: 'Dairy & Eggs',
    items: [
      { name: 'Egg (large)', kcal: 72, protein_g: 6, fat_g: 5 },
      { name: 'Egg white (large)', kcal: 17, protein_g: 4 },
      { name: 'Scrambled eggs (2 eggs)', kcal: 182, protein_g: 13, fat_g: 14 },
      { name: 'Greek yogurt (150g)', kcal: 133, protein_g: 15, fat_g: 5, carb_g: 6 },
      { name: 'Natural yogurt (150g)', kcal: 86, protein_g: 7, fat_g: 4, carb_g: 6 },
      { name: 'Skyr (150g)', kcal: 90, protein_g: 15, fat_g: 0, carb_g: 6 },
      { name: 'Cottage cheese (100g)', kcal: 98, protein_g: 11, fat_g: 4, carb_g: 3 },
      { name: 'Ricotta (50g)', kcal: 87, protein_g: 5, fat_g: 7, carb_g: 2 },
      { name: 'Cheddar cheese (30g)', kcal: 120, protein_g: 7, fat_g: 10 },
      { name: 'Mozzarella (30g)', kcal: 80, protein_g: 6, fat_g: 6 },
      { name: 'Parmesan (15g)', kcal: 61, protein_g: 5, fat_g: 4 },
      { name: 'Cream cheese (30g)', kcal: 98, protein_g: 2, fat_g: 10 },
      { name: 'Whole milk (250ml)', kcal: 152, protein_g: 8, fat_g: 8, carb_g: 12 },
      { name: 'Skimmed milk (250ml)', kcal: 86, protein_g: 8, fat_g: 0, carb_g: 12 },
      { name: 'Butter (10g)', kcal: 72, fat_g: 8 },
    ],
  },
  {
    category: 'Drinks',
    items: [
      { name: 'Water (500ml)', kcal: 0 },
      { name: 'Cup of coffee (black)', kcal: 2 },
      { name: 'Coffee with milk', kcal: 30, protein_g: 2, fat_g: 1 },
      { name: 'Latte (250ml)', kcal: 120, protein_g: 6, fat_g: 5, carb_g: 10 },
      { name: 'Flat white (200ml)', kcal: 100, protein_g: 5, fat_g: 4, carb_g: 9 },
      { name: 'Cappuccino (200ml)', kcal: 80, protein_g: 4, fat_g: 3, carb_g: 8 },
      { name: 'Cup of tea (black)', kcal: 1 },
      { name: 'Tea with milk', kcal: 20, protein_g: 1 },
      { name: 'Coke (330ml)', kcal: 139, carb_g: 35 },
      { name: 'Diet Coke (330ml)', kcal: 1 },
      { name: 'Sparkling water (330ml)', kcal: 0 },
      { name: 'Orange juice (250ml)', kcal: 112, carb_g: 26 },
      { name: 'Apple juice (250ml)', kcal: 115, carb_g: 28 },
      { name: 'Oat milk (250ml)', kcal: 130, protein_g: 3, fat_g: 5, carb_g: 17 },
      { name: 'Almond milk (250ml)', kcal: 30, protein_g: 1, fat_g: 3, carb_g: 1 },
      { name: 'Soy milk (250ml)', kcal: 90, protein_g: 7, fat_g: 4, carb_g: 6 },
      { name: 'Sports drink (500ml)', kcal: 150, carb_g: 36 },
      { name: 'Energy drink (250ml)', kcal: 110, carb_g: 28 },
      { name: 'Protein shake (scoop)', kcal: 120, protein_g: 25, carb_g: 4, fat_g: 2 },
      { name: 'Beer (330ml)', kcal: 142, carb_g: 13 },
      { name: 'Wine, red (175ml)', kcal: 143, carb_g: 4 },
      { name: 'Wine, white (175ml)', kcal: 130, carb_g: 4 },
    ],
  },
  {
    category: 'Nuts & Spreads',
    items: [
      { name: 'Almonds (30g)', kcal: 174, protein_g: 6, fat_g: 15, carb_g: 6 },
      { name: 'Cashews (30g)', kcal: 163, protein_g: 4, fat_g: 13, carb_g: 9 },
      { name: 'Walnuts (30g)', kcal: 196, protein_g: 5, fat_g: 20, carb_g: 4 },
      { name: 'Mixed nuts (30g)', kcal: 180, protein_g: 5, fat_g: 16, carb_g: 6 },
      { name: 'Peanut butter (1 tbsp)', kcal: 94, protein_g: 4, fat_g: 8, carb_g: 3 },
      { name: 'Almond butter (1 tbsp)', kcal: 98, protein_g: 3, fat_g: 9, carb_g: 3 },
      { name: 'Hummus (2 tbsp)', kcal: 70, protein_g: 3, fat_g: 5, carb_g: 5 },
      { name: 'Cream cheese (1 tbsp)', kcal: 49, protein_g: 1, fat_g: 5 },
      { name: 'Jam / marmalade (1 tbsp)', kcal: 49, carb_g: 13 },
      { name: 'Honey (1 tbsp)', kcal: 64, carb_g: 17 },
      { name: 'Olive oil (1 tbsp)', kcal: 119, fat_g: 14 },
    ],
  },
  {
    category: 'Snacks & Sweets',
    items: [
      { name: 'Rice cake (plain)', kcal: 35, carb_g: 7 },
      { name: 'Oat cake (1 piece)', kcal: 44, carb_g: 7, protein_g: 1, fat_g: 2 },
      { name: 'Granola bar', kcal: 193, carb_g: 29, protein_g: 4, fat_g: 7 },
      { name: 'Protein bar (avg)', kcal: 200, protein_g: 20, carb_g: 22, fat_g: 6 },
      { name: 'Energy bar (avg)', kcal: 220, protein_g: 8, carb_g: 30, fat_g: 7 },
      { name: 'Dark chocolate (30g)', kcal: 170, fat_g: 12, carb_g: 13, protein_g: 2 },
      { name: 'Milk chocolate (30g)', kcal: 160, fat_g: 9, carb_g: 18, protein_g: 2 },
      { name: 'Medjool date (1 piece)', kcal: 66, carb_g: 18 },
      { name: 'Banana bread (slice)', kcal: 196, carb_g: 33, protein_g: 3, fat_g: 6 },
      { name: 'Crisps / chips (25g bag)', kcal: 132, carb_g: 14, fat_g: 8 },
      { name: 'Popcorn (30g)', kcal: 110, carb_g: 23, fat_g: 1, protein_g: 3 },
      { name: 'Biscuit / cookie (1 piece)', kcal: 67, carb_g: 9, fat_g: 3 },
      { name: 'Waffle (plain)', kcal: 218, carb_g: 25, protein_g: 6, fat_g: 11 },
      { name: 'Pancake (plain, medium)', kcal: 86, carb_g: 11, protein_g: 2, fat_g: 4 },
    ],
  },
]
